### ISSUE TITLE
groupConsecutivelyBy of Iterable gives wrong result

### ISSUE THREAD

**Issue by jyuhuan** [ctongfei/poly-collection#21]
The following code snippet is a minimal example to reproduce this issue:

```scala
import cats.instances.all._
val xs: Iterable[Int] = ArraySeq(1, 4, 7, 2, 5, 2, 0, 3, 1)
val ys = xs.groupConsecutivelyBy(_ % 3)
```

`ys` is expected to be `((1, 4, 7), (2, 5, 2), (0, 3), (1))`, yet what was actually produced was `((1), (4, 7), (2, 5, 2), (0, 3), (1))`.

**Comment by ctongfei** [comment]
fixed https://github.com/ctongfei/poly-collection/commit/dc255a74bb86b3cf23720b75346d2c50c0ce682a
